services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOST: 0.0.0.0
        PORT: 8765
    container_name: mcp-server
    ports:
      - "8765:8765"
    restart: unless-stopped